### ISSUE TITLE
Rename and extend Boxplot class

### ISSUE THREAD

**Issue by meatballs** [drvinceknight/Axelrod#105]
Rename and extend the BoxPlot class so that it also processes the payoff plots thus:
 
* Simplifying run_tournament
* Allowing the elements of the payoff plot, currently in run_tournament, to become individual methods which can be included in the test suite
* Only checking for matplotlib installation once - in the class

**Comment by meatballs** [comment]
I'll pick this one up as long as everyone is happy for it to happen.

**Comment by drvinceknight** [comment]
This look great meatballs.

**Comment by drvinceknight** [comment]
(that was meant to be @meatballs, on my phone, don't seem able to edit)

**Comment by meatballs** [comment]
OK - I'll get started when I get a mo

**Comment by meatballs** [comment]
This is on branch 105 in my fork. I'll create at PR when I'm done.
