### ISSUE TITLE
Fool Me Once and Grudger

### ISSUE THREAD

**Issue by meatballs** [drvinceknight/Axelrod#106]
My apologies if I'm missing something, but aren't the 'Fool Me Once' and 'Grudger' strategies the same strategy with different implementations in code?

**Comment by drvinceknight** [comment]
EEEk, let me take a look: I might have missed that.

**Comment by drvinceknight** [comment]
No, `Fool me once` won't start 'grudging' until a second defection. `Grudger` however will defect forever once it has been defected against (once).

**Comment by meatballs** [comment]
Ah yes. I thought I might be missing something!

**Comment by drvinceknight** [comment]
Thanks for raising it though: much appreciated.
