### ISSUE TITLE
Re-write README.md in rest

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/Axelrod#119]
Based on hitchhikers guide this is apparently needed for Pypi.

**Comment by meatballs** [comment]
http://bfroehle.com/2013/04/26/converting-md-to-rst/

**Comment by drvinceknight** [comment]
Nice. Running that now :)

**Comment by drvinceknight** [comment]
b63c6da0b493cbebcd214a3ce5503a39e29e8597 and 19a44746176a303c73c08b6a4297e32eaddcb132
