### ISSUE TITLE
Ecological tournament variant

### ISSUE THREAD

**Issue by langner** [drvinceknight/Axelrod#28]
I'm not sure if it was organized by Axelrod, but there was a subsequent "ecological" tournament where each strategy was represented by some number of copies. The tournament consisted of ~1000 generations, and at the beginning of each generation the population of a strategy was set based on its score in the previous round.

This interesting variant could be easily built on top of the current code.

**Comment by langner** [comment]
Of course, this tournament can be based on the average payoff matrix determined in the round robin phase.

**Comment by drvinceknight** [comment]
I'd not heard of this subsequent tournament: sounds like a great idea though. I wrote some code that allowed for a genetic algorithm to be applied to any normal form game (I used it for this screencast: https://www.youtube.com/watch?v=Tz-lZy0AKRI)... I like the idea of this :+1:

**Comment by drvinceknight** [comment]
Not sure if the PR is still coming: just a thought that it could be nice to start seperating things. So this could live in it's own file under `axelrod/`? Similarly I might pull the players out in to their own file... Just to keep things tidy. Any reason not to do this?

**Comment by drvinceknight** [comment]
*BOOM* @langner killed this one with 062be93e19c19594832744806d23f24f32bb2a8b :D
