### ISSUE TITLE
Write a manage.py script

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/Axelrod#32]
As the number of strategies grows: the mathces (or just the random repetitions) can be parallelised (possibly even making use of caching for non stochastic strategies...).

**Comment by drvinceknight** [comment]
I'm going to incorporate this with a new `manage.py` script which will run everything:

- options to run tests
- options to run in parallel
- etc?

**Comment by langner** [comment]
At first glance, caching would be the first things to do to boost performance.

**Comment by langner** [comment]
See #41 for caching for pairs of deterministic strategies.

**Comment by drvinceknight** [comment]
Absolutely huge pull request! Amazing! Awesome @langner ! I'll leave this issue open as I still want to parallelise when I get a chance. That does need the overall better `manage.py` script which I'll get to.

**Comment by drvinceknight** [comment]
(I am learning a lot of Python from your pull request @langner : very much appreciated).

**Comment by meatballs** [comment]
Can this one be closed now?

**Comment by drvinceknight** [comment]
I think I'd still like a manage.py script, which we don't have so that we could move the functionality of `run_tournament` and include options like:

```
manage.py test
```

actually that's the only extra thing I'd want in there that I can think off.. Perhaps not needed?

**Comment by meatballs** [comment]
why not just add any additional functionality as methods in the TournamentManager class? Makes them much easier to test.

**Comment by drvinceknight** [comment]
Does it make sense to have `run tests` in there? I think that's the only
extra thing really needed which I'm now not sure warrants it... Although I
guess could be nice...

**Comment by meatballs** [comment]
Probably doesn't make much sense. Anyone who knows enough to want to run the tests is going to be perfectly capable of typing the command to do so. Running tests from within TournamentManager would actually require more typing!

**Comment by drvinceknight** [comment]
Yeah... Cool. Let's scrap this.
