### ISSUE TITLE
Infinite recursion

### ISSUE THREAD

**Issue by langner** [drvinceknight/Axelrod#33]
What happens when a geller encounters another geller?

**Comment by drvinceknight** [comment]
This already occurred when geller encountered mindreader: it's in issue #22  https://github.com/drvinceknight/Axelrod/issues/22

I've got a 'cheaters' branch where we have the error... I'm going to write a `manage.py` script which give more granular control than the current `run_tournament.py`, that'll also be a step towards dealing with this. All ideas welcome though :)

**Comment by langner** [comment]
OK
