### ISSUE TITLE
Make each test runable as standalone

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/Axelrod#83]
Need to add code to bottom of every test script... (Why did I not do this to start?)

```
if __name__ == '__main__':
    unittest.main()
```

**Comment by meatballs** [comment]
I don't think this is necessary. Any test can be run standalone without this code. For example, test_alternator.py does not have the line but can be run with:

```python
python -m unittest axelrod.tests.test_alternator
```

**Comment by drvinceknight** [comment]
I don't think I realised you could run it with that command...
