### ISSUE TITLE
Create a BoxPlot class

### ISSUE THREAD

**Issue by meatballs** [drvinceknight/Axelrod#88]
This class should handle the production of a matlibplot boxplot based on a ResultSet instance passed to its init method.

The functions to generate the boxes/whiskers, xticks, and title should be separate methods with tests for each.

The method which would return an instance of matlibplot.Figure probably cannot be tested as Travis does not have matlibplot installed.

run_tournament.py would handle the creation of .png files based on the Figure object returned from this class.

**Comment by drvinceknight** [comment]
Tagging myself in as I think I can help with this one.

**Comment by meatballs** [comment]
I've made a start on this one - branch 88 in my fork.

**Comment by drvinceknight** [comment]
:+1: Will try to get to it.

**Comment by drvinceknight** [comment]
Also, pretty sure we can add matplotlib as a dependency on travis... Let me go check that...

**Comment by drvinceknight** [comment]
Yeah looks fine:

http://docs.travis-ci.com/user/languages/python/

Here's a SO question (mainly due to a problem with python 3 so not relevant): http://stackoverflow.com/questions/1739494/travis-ci-matplotlib-dependency-and-python3

**Comment by meatballs** [comment]
I'm hitting the matlibplot problem again - must be something I don't understand about the library.

Line 47 in run_tournament.py ought to give the same results as line 48, but doesn't.

**Comment by drvinceknight** [comment]
I've got some time, so taking a look now.

**Comment by drvinceknight** [comment]
Found the error somewhere, I think your numpy array is carrying out integer division... Finding where that happens now.

**Comment by drvinceknight** [comment]
Think I've fixed it: sending you a PR (apologies in advance if I just confused myself).

**Comment by drvinceknight** [comment]
Ok, I think I have to actually 'request that you pull', I can't seem to get github to send you a nice pull request as I did not fork your fork...

https://github.com/drvinceknight/Axelrod/tree/88

Let me know if that doesn't work :) :+1:

**Comment by drvinceknight** [comment]
That branch failed on travis for me by the way (but I just checked that outputs where the same, didn't run tests).

**Comment by meatballs** [comment]
I'll have a look some time tomorrow - thanks for the help

**Comment by drvinceknight** [comment]
My pleasure (if I understood the issue correctly obviously).

**Comment by meatballs** [comment]
Yep - that works!! (But why did that need adding to the method, when it's not required within run_tournament.py)?

I'll finish this off and submit a PR when I'm done

**Comment by drvinceknight** [comment]
> Yep - that works!!

Awesome!

> (But why did that need adding to the method, when it's not required within run_tournament.py)?

Because at the top of `run_tournament` we tweak the division: `from __future__ import division`. I wouldn't want to do this throughout `axelrod` but in a script that makes use of the library I thought it was fine. When we eventually package this so that people can run all sorts of different types of tournaments I'd want them to know that 'normal' Python 2 division is still going (even though it's a pain).

Any chance of you de-numpying? No problem if not, can get to that at another time.

**Comment by meatballs** [comment]
Agggghhhhhhh!!!! Missed that subtlety entirely!!!

OK - I'll sort out the de-numpification and the try-catch for matplotlib before I create the PR.

**Comment by drvinceknight** [comment]
(By the way: the test suite you wrote, really is excellent I'm just writing a bunch of tests for #52 and it makes it really easy: thanks!)

> Agggghhhhhhh!!!! Missed that subtlety entirely!!!

Hehe, yeah pretty much my first go to when debugging Python: 'integer division'?

Really no problem if the de-numpy thing doesn't happen, I expect that'll be a weekend job to go through everything at some point...

**Comment by meatballs** [comment]
On second thoughts, I'll leave the de-numpification for a separate PR.

**Comment by drvinceknight** [comment]
Yeah, completely fine: we're in transition :D

**Comment by meatballs** [comment]
> (By the way: the test suite you wrote, really is excellent I'm just writing a bunch of tests for #52 and it makes it really easy: thanks!)

You're welcome. I had to write it to understand properly what most of the code was actually doing!!
